CREATE TABLE observal_data (
	id INT auto_increment PRIMARY KEY,
	patient_id VARCHAR ( 10 ) NULL COMMENT '孕妇住院号',
	ep_placement_point_id INT NULL COMMENT '硬膜外穿刺点位置',
	observal_end_point_id INT NULL COMMENT '观察终点',
	cervix_fully_dilated_time VARCHAR ( 8 ) NULL COMMENT '宫口开全时间',
	cervix_dilatation INT NULL COMMENT '宫颈扩张度',
	initial_time VARCHAR ( 8 ) NULL COMMENT '麻醉开始时间',
	initial_dose INT NULL COMMENT '负荷剂量(ml)',
	pump_consumption INT NULL COMMENT '泵消耗(ml)',
	bolus INT NULL COMMENT '人工负荷量(ml)',
	pca_count INT NULL COMMENT 'PCA次数',
	manual_bolus_count INT NULL COMMENT '人工硬膜外追加次数',
	first_pca_time VARCHAR ( 8 ) NULL COMMENT '首次PCA时间',
	has_vasoactive_agent TINYINT ( 1 ) DEFAULT '0' NULL COMMENT '是否使用血管活性药物',
	first_manual_bolus_time VARCHAR ( 8 ) NULL COMMENT '首次人工硬膜外追加时间',
	has_hypotension TINYINT ( 1 ) DEFAULT '0' NULL COMMENT '是否有血压过低',
	has_caesarean_section TINYINT ( 1 ) DEFAULT '0' NULL COMMENT '是否有剖宫产',
	has_instrumental TINYINT ( 1 ) DEFAULT '0' NULL COMMENT '是否有器械助产',
	has_lateral_episiotomy TINYINT ( 1 ) DEFAULT '0' NULL COMMENT '是否有侧切',
	birth_time VARCHAR ( 8 ) NULL COMMENT '分娩时间',
	foetal_weight INT NULL COMMENT '胎儿体重',
	one_minute_apgar_score INT NULL COMMENT '1分钟APGAR评分',
	five_minute_apgar_score INT NULL COMMENT '5分钟APGAR评分',
	description VARCHAR ( 1000 ) NULL COMMENT '备注',
	ctime DATETIME NULL,
	utime DATETIME NULL,
	dtime DATETIME NULL,
CONSTRAINT observal_data_id_uindex UNIQUE ( id )
) COMMENT '观察数据';
